id=Id
firstname=Firstname
lastname=Lastname
role=Role
supervisor=Supervisor

addEmployee=Add Employee
editEmployee=Edit Employee
removeEmployee=Remove Employee
ListPage.removeEmployeeWithSubordinatesLabel=Remove Employee with Subordinates
listSubordinates=List Subordinates
ListPage.next=Next Page
ListPage.previous=Previous Page

Role.MANAGER=Manager
Role.CEO=CEO
Role.EMPLOYEE=Employee